apiVersion: v1
kind: Service
metadata:
  name: healthpair-front
  labels:
    app: healthpair
    role: front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: healthpair
    role: front